const input  = document.querySelector("input");
const button  = document.querySelector("button");
const details = document.querySelector(".details");
button.addEventListener("click",async function(){
    details.innerText="";
    const res = await axios.get(`https://api.openweathermap.org/geo/1.0/direct?q=${input.value}&limit=1&appid=6b634582c232e651d404243ef2997255`)
    const lat = res.data[0].lat;
    const lon = res.data[0].lon;
    const final = await axios.get(`https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=6b634582c232e651d404243ef2997255`)
    const span1 = document.createElement("span");
    const span2 = document.createElement("span");
    const span3 = document.createElement("span");
    const sup = document.createElement("sup");
    sup.innerText="o";
    span1.innerText = `Maximum Tempature - ${Math.round(final.data.main.temp_max-273)}`;
    span2.appendChild(sup);
    span3.innerText="C";
    const div = document.createElement("div");
    div.appendChild(span1);
    div.appendChild(span2);
    div.appendChild(span3);
    details.appendChild(div);
    const div1 = document.createElement("div");
    const span11 = document.createElement("span");
    const span22 = document.createElement("span");
    const span33 = document.createElement("span");
    const sup1 = document.createElement("sup");
    sup1.innerText="o";
    span11.innerText = `Minimum Tempature - ${Math.round(final.data.main.temp_min-273)}`;
    span22.appendChild(sup1);
    span33.innerText="C";
    div1.appendChild(span11);
    div1.appendChild(span22);
    div1.appendChild(span33);
    details.appendChild(div1);
    const div2 = document.createElement("div");
    const span111 = document.createElement("span");
    const span222 = document.createElement("span");
    span222.innerText = final.data.weather[0].description;
    span111.innerText = final.data.weather[0].main+":  - ";
    div2.appendChild(span111);
    div2.appendChild(span222);
    details.appendChild(div2);
    const rise = new Date(final.data.sys.sunrise *1000);
    const set = new Date(final.data.sys.sunset*1000);
    const rise_final = rise.toUTCString();
    const set_final  = set.toUTCString();
    const rise_1 = new Date(Date.parse(rise_final));
    const rise_final1 = rise_1.toLocaleTimeString();
    const set_1 = new Date(Date.parse(set_final));
    const set_final1 = set_1.toLocaleTimeString();
    const div_rise = document.createElement("div");
    const div_set = document.createElement("div");
    div_rise.innerText = "Sunrise time: - "+rise_final1;
    div_set.innerText = "Sunset time: - "+set_final1;
    details.appendChild(div_rise);
    details.appendChild(div_set);
    console.log(final.data);
    input.value="";
})